server:
  port: 8443

spring:
  profiles:
    active: dev
#  mvc:
#    view:
#      prefix: /WEB-INF/views/jsp/
#      suffix: .jsp

logging:
  level:
    ROOT: INFO
    org.springframework: INFO
    org.springframework.data: ERROR
    com.epam.martseniuk: DEBUG