server:
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: classpath:test.p12
    key-store-password: test
    key-alias: test
    trust-store-type: PKCS12
    trust-store: classpath:localhost-trust-store.p12
    trust-store-password: 1
    client-auth: need